language: node_js
node_js:
  - 8
before_script:
  - 'npm run bootstrap'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
